% function Out=SPGRfM(T1s,PDs,FAs,TR)
function Out=SPGRfM(T1s,PDs,FAs,TR)
nFAs=numel(FAs);
n=numel(T1s);
TRM=repmat(TR,[n 1]);
T1M=repmat(T1s',[1 nFAs]);
PDM=repmat(PDs',[1 nFAs]);
E1=exp(-TRM./T1M);
SFAM=repmat(sind(FAs),[n 1]);
CFAM=repmat(cosd(FAs),[n 1]);
Out=PDM.*(1-E1).*SFAM./(1-E1.*CFAM);